<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class AttendanceQrCode extends Model
{
    use HasFactory;

    protected $fillable = [
        'token',
        'expires_at',
        'generated_by',
    ];

    protected function casts(): array
    {
        return [
            'expires_at' => 'datetime',
        ];
    }

    /**
     * The admin who manually force-refreshed this code.
     * Null means it was generated by the scheduled rotation, not a person.
     */
    public function generatedByAdmin(): BelongsTo
    {
        return $this->belongsTo(User::class, 'generated_by');
    }

    public function logs(): HasMany
    {
        return $this->hasMany(AttendanceLog::class, 'qr_code_id');
    }

    public function isExpired(): bool
    {
        return $this->expires_at->isPast();
    }

    /**
     * Scope to codes that are still live (not yet expired).
     */
    public function scopeActive(Builder $query): Builder
    {
        return $query->where('expires_at', '>', now());
    }
}
